HEADSCALE_VERSION=0.28.0
HEADPLANE_VERSION=latest

DOMAIN=${DOMAIN}
HEADSCALE_DOMAIN=${HEADSCALE_DOMAIN}
HEADPLANE_DOMAIN=${HEADPLANE_DOMAIN}
AUTH_DOMAIN=${AUTH_DOMAIN}

HEADSCALE_URL=http://headscale:8080
HEADSCALE_PUBLIC_URL=https://${HEADSCALE_DOMAIN}
HEADPLANE_SERVER__BASE_URL=https://${HEADPLANE_DOMAIN}
HEADPLANE_SERVER__COOKIE_SECRET=${HEADPLANE_SERVER__COOKIE_SECRET}
HEADPLANE_SERVER__INFO_SECRET=${HEADPLANE_SERVER__INFO_SECRET}
HEADSCALE_API_KEY=${HEADSCALE_API_KEY}
HEADSCALE_OIDC_CLIENT_SECRET=${HEADSCALE_OIDC_CLIENT_SECRET}

SERVER_URL=https://${HEADSCALE_DOMAIN}
DNS_BASE_DOMAIN=tailnet.${DOMAIN}
