services:
  app:
    ports:
      - "3001:3000"

  bulwark-web:
    ports:
      - "3000:3000"

  listmonk-app:
    ports:
      - "9000:9000"

  postal-web:
    ports:
      - "5000:5000"

  libredesk-app:
    ports:
      - "9001:9000"

  stalwart-config:
    environment:
      - STALWART_CONFIG_PATH=/opt/stalwart/etc/config.toml
    volumes:
      - ./scripts/stalwart:/scripts:ro
      - stalwart_data:/opt/stalwart
      - /var/run/docker.sock:/var/run/docker.sock:ro

  stalwart:
    volumes:
      - stalwart_data:/opt/stalwart
    ports:
      - "8080:8080"
