services:
  app:
    image: docker.io/jc21/nginx-proxy-manager:${NPM_VERSION:-latest}
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      INITIAL_ADMIN_EMAIL: ${NPM_ADMIN_EMAIL:?NPM_ADMIN_EMAIL is required}
      INITIAL_ADMIN_PASSWORD: ${NPM_PASSWORD:?NPM_PASSWORD is required}
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
